using System.Drawing;
using System.Globalization;
using FastColorFinder.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StateMachine.Automation;

// Reads the text generated by FastColorFinder's CopyCallCodeAsync. No code is executed.
public sealed record ColorFeatureImport(string WeightString, Rectangle? SearchRange, int? ColorDeviation, double? Similarity)
{
    public static ColorFeatureImport Read(string text)
    {
        text = text.Trim().TrimStart('\uFEFF').Trim();
        if (text.StartsWith("FCF2|", StringComparison.Ordinal) || text.StartsWith("FCF3|", StringComparison.Ordinal))
            return new(ColorModelCodec.Encode(ColorModelCodec.Decode(text)), null, null, null);

        var root = CSharpSyntaxTree.ParseText(text).GetRoot();
        var strings = root.DescendantTokens().Where(t => t.IsKind(SyntaxKind.StringLiteralToken))
            .Select(t => t.ValueText).Where(s => s.StartsWith("FCF2|", StringComparison.Ordinal) || s.StartsWith("FCF3|", StringComparison.Ordinal))
            .Distinct().ToArray();
        if (strings.Length != 1) throw new FormatException("请粘贴工具的完整调用代码，或单独的 FCF2 / FCF3 权重字符串。");
        var weights = ColorModelCodec.Encode(ColorModelCodec.Decode(strings[0]));
        var call = root.DescendantNodes().OfType<InvocationExpressionSyntax>()
            .FirstOrDefault(i => i.Expression.ToString().EndsWith("FastColorSearch.FindAsync", StringComparison.Ordinal));
        Rectangle? range = null;
        int? deviation = null;
        double? similarity = null;
        if (call is not null)
        {
            var rectangle = call.ArgumentList.Arguments.FirstOrDefault()?.Expression as ObjectCreationExpressionSyntax;
            if (rectangle?.Type.ToString() is "Rectangle" or "System.Drawing.Rectangle" && rectangle.ArgumentList?.Arguments.Count == 4)
            {
                var values = rectangle.ArgumentList.Arguments.Select(a => ReadInteger(a.Expression)).ToArray();
                if (values[2] <= 0 || values[3] <= 0) throw new FormatException("调用代码中的查找范围宽高必须大于零。");
                range = new(values[0], values[1], values[2], values[3]);
            }
            foreach (var argument in call.ArgumentList.Arguments)
            {
                switch (argument.NameColon?.Name.Identifier.ValueText)
                {
                    case "colorDeviation":
                        deviation = ReadInteger(argument.Expression);
                        if (deviation is < 0 or > 255) throw new FormatException("调用代码中的色偏应在 0～255 之间。");
                        break;
                    case "similarityThreshold":
                        similarity = ReadNumber(argument.Expression);
                        if (similarity is <= 0 or > 100) throw new FormatException("调用代码中的相似度应在 1～100 之间。");
                        break;
                }
            }
        }
        return new(weights, range, deviation, similarity);
    }

    public void ApplyTo(ColorProbeSettings settings)
    {
        settings.WeightString = WeightString;
        if (SearchRange is { } range)
        { settings.X = range.X; settings.Y = range.Y; settings.Width = range.Width; settings.Height = range.Height; }
        if (ColorDeviation.HasValue) settings.ColorDeviation = ColorDeviation.Value;
        if (Similarity.HasValue) settings.Similarity = Similarity.Value;
    }

    private static int ReadInteger(ExpressionSyntax expression)
    {
        var value = ReadNumber(expression);
        if (value < int.MinValue || value > int.MaxValue || value != Math.Truncate(value))
            throw new FormatException("调用代码中的坐标、范围及色偏必须是整数。");
        return (int)value;
    }
    private static double ReadNumber(ExpressionSyntax expression)
    {
        if (expression is PrefixUnaryExpressionSyntax unary && (unary.IsKind(SyntaxKind.UnaryMinusExpression) || unary.IsKind(SyntaxKind.UnaryPlusExpression)))
            return (unary.IsKind(SyntaxKind.UnaryMinusExpression) ? -1 : 1) * ReadNumber(unary.Operand);
        if (expression is LiteralExpressionSyntax literal && literal.IsKind(SyntaxKind.NumericLiteralExpression))
        {
            var value = Convert.ToDouble(literal.Token.Value, CultureInfo.InvariantCulture);
            if (double.IsFinite(value)) return value;
        }
        throw new FormatException("调用代码中的参数需要是工具生成的具体数值。");
    }
}
